# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4c66e1cf708fbdd09e3bdb74a87f261b519cd5ccc5b6cd1cdd9566d4f3ca2d1176746aaf6dfcdf388ca42e9d0e572f5756dbdabf93d27106592c190ad6e3d74

test:
  secret_key_base: acc561afaf591c8cda41a919c5cf6a7a2a6b3d06704fa73311a5e83bdc7da6c96cd6346761a81fdbd779b550a1f01df4e2dba9fcbd369aace00d1c200f6b900b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
